import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "@/styles/Index.module.sass";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
    const settings = {
        dots: true,
        infinite: true,
        speed: 500,
        slidesToShow: 1,
        slidesToScroll: 1
    };

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className={styles.homePage}>
                <h1 className={styles.testLink}>
                    <p>Job Posting <Link href="./jobPostings">Page</Link></p>
                </h1>
            </div>
        </>
    );
}
